### ISSUE TITLE
Is `geopandas` a hard dependency for `esda` now?

### ISSUE THREAD

**Issue by weikang9009** [pysal/esda#119]
Is `geopandas` a hard dependency for `esda` now?

[adbscan imports geopandas](https://github.com/pysal/esda/blob/master/esda/adbscan.py#L10):
```python
from geopandas import GeoSeries
```

**Comment by darribas** [comment]
Good catch! Yes, as of now it is.  However, it's only called to instantiate the return of clusters found:

https://github.com/pysal/esda/blob/c0118207bbf6427e4d7ab2637441d9ae9f4745d9/esda/adbscan.py#L519

So we could remove the hard requirement. If the machine has `geopandas`, it returns a `GeoSeries` (a lot more convenient), otherwise it returns a list of `shapely` polygons from the alpha shape algo.

This is if we don't want to make it a hard dependency, that is. I'm ambivalent.

**Comment by jGaboardi** [comment]
This has been [resolved](https://github.com/pysal/esda/blob/ec12837871b20b7b79c2c7bef813025459f22188/esda/adbscan.py#L505-L510).
