### ISSUE TITLE
Issues with assuncao_rate function and NaN

### ISSUE THREAD

**Issue by timstallmann** [pysal/esda#126]
Hi! 

I haven't worked this into test case data that would be shareable yet, but am using `pysal.esda.moran.Moran_Rate` in some code and running into `nan` output. 

Debugging the code, it appears that the `assuncao_rate` smoother function does not include a check for negative values of `ebi_v`, which then leads to NaN values in the EB-adjusted rates values which propagate through all the calculations.

Assunçao's original paper says that, by convention, if `ebi_v[i] < 0`, then it should be set to `ebi_v[i] = ebi_b / b[i]`, rather than `ebi_a + ebi_b / b[i]`. Am I wrong in thinking this should also be in the PySAL code? I have implemented the fix locally and happy to submit a PR.

**Comment by jonnyhuck** [comment]
Hi both, I think that I might be running into the same issue here (nan output from Moran_Rate) - I can't see the PR referenced above anywhere - did you ever reach a conclusion on this?

**Comment by ljwolf** [comment]
I've gotten an email notification from @jonnyhuck about this, but for some reason the comment isn't appearing on the package itself. Yes, the fix would easily be incorporated and I think is a correct read of the source paper (p. 2157 para 2)!

**Comment by jonnyhuck** [comment]
Hi @ljwolf - apologies - I had removed the comment as I did some more digging and found that it was a slightly different issue in the same `assuncao_rate` caused by one instance of my effect and population values both being 0. However, if you are going to edit the function this might be a good opportunity for raising a ValueError or similar. This  situationwould not be caught by the suggested fix (i tried it). 

I can provide details of exactly where the issue occurs (would just have to work it out again...), or propose a pull for that case if you like?

**Comment by ljwolf** [comment]
Details are helpful, and a PR would be awesome! Happy to review & integrate any changes.

**Comment by jonnyhuck** [comment]
That is odd - it isn't reflected here: https://github.com/pysal/esda/blob/master/esda/smoothing.py#L563

This might be down to my understanding of the interaction of the modules - but it certainly isn't reflected in my version from Anaconda either.

**Comment by ljwolf** [comment]
Indeed, I'm not sure if there's been an issue with the migration of the federating of `pysal` (where we migrated this stuff from `pysal` to the `esda` package) but the fix should be made here now. 

This is odd. 

Happy to merge the fix and do a bugfix release asap.
