### ISSUE TITLE
Spatial cross-correlations?

### ISSUE THREAD

**Issue by ninamiolane** [pysal/esda#141]
Hello, thank you for a great package! Would you have measures of spatial *cross-*correlations (as opposed to auto-correlations) available? Alternatively, would you know of python packages implementing some, with associated pairs of Moran-I-type scatterplots?

Thank you!

Reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4438072/
A New Methodology of Spatial Cross-Correlation Analysis

**Comment by sjsrey** [comment]
Not sure if this is what you are looking for, but maybe the [bivariate Moran](http://pysal.org/notebooks/viz/splot/esda_morans_viz.html) would be of interest?

**Comment by ninamiolane** [comment]
Hi, thank you for your very quick answer! Bivariate Moran could help, but only partially (if I understood correctly). 

I would be interested in a multivariate Moran-type statistic that can tell if: 
- u_1, u_2 -> X(u_1, u_2) in R^n; and
- u_1, u_2 -> Y(u_1, u_2) in R^m

are correlated. (i.e. two multivariate spatial fields X and Y). I am not interested in the autocorrelation for X nor Y.

If X and Y are univariate, then I can concatenate them and compute the bivariate Moran. But the bivariate Moran would also take into account the autocorrelations within X and within Y. Does it have a method that would only show the cross-correlation between X and Y?

Thank you very much!

**Comment by ljwolf** [comment]
Thanks for the ref & clarification! I hope we can get what you need.

**Before going into the Chen paper,** it has `x` and `y` as the same shape, and univariate... In your second comment, you have 
- two fields, one `Y` with `m` measurement sites and another `X` with `n` measurement sites. 
- You observe `p` variates in both fields, 
- and want to know the correlation between the site measurements in `Y` to near sites in `X`? 

Off the cuff, I think you can construct the `(n,m)` distance matrix (say... using `scipy.spatial.distance.cdist` or a knn-based sparser version) and use `X.T @ W @ Y` if X is `(n,p)`, `W` is `(n,m)` & [doubly-standardized](https://en.wikipedia.org/wiki/Doubly_stochastic_matrix), and `Y` is `(m,p)`. We definitely don't have something like this right now since we 
- don't generally support `(n,m)` weights matrices, and 
- don't have doubly-stochastic standardization for them. 

If we did, this would be something like a "bivariate cross-field moran statistic" I guess?

**On the linked Chen paper**... their expression for `R_c` (Eqs. 9 & 10) is the same as the bivariate expression arising from Eq. 4 in [Wartenburg (1980)](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1538-4632.1985.tb00849.x): they're both `y.T @ W @ x`. Chen is defining `W` to be unit-standardized rather than row-standardized (which is more common in the calculation of Moran coefficients, sure) but the form is the same. The Bivariate Moran (as `R_c`) doesn't account for autocorrelation in either `x` or `y`: it's only about the spatial cross-correlation between `x` and `y` weighted by `W`, or (another interpretation) the dependence of `y` on the spatial lag `W @ x`. 

Later equations (11 on, basically)... we don't have that.

Hope that helps...

**Comment by ninamiolane** [comment]
Thank you so much for your quick and detailed answer!

In my situation, X and Y can also have a different number of covariates, say p and q, but it does not change much.

The (n, m) weight matrix would definitely work, thank you. We would get a full matrix (p, p) or (p, q) of "bivariate cross-field moran I", and could perform independence testing for each pair of the covariates' coordinates. Thank you also for the clarification on the `R_c`.

This was very helpful, can't wait to use `esda` more.

**Comment by ekcomputer** [comment]
I just stumbled upon this thread, while having the same issue.

How about concatenating the datasets, as you suggest, computing full or KNN weights, but then removing all cross-dataset weights?  The weight matrix would then have null entries in the upper-left and lower-right quadrants, so the only spatial information would be between the two datasets. If using KNN, you would have to use a large enough K to ensure you get some between-datasets linkage, or find an alternate way of selecting linkages only between datasets. This would guarantee that your weights matrix is square, but the only question is whether or not it violates any assumptions used by the Bivariate Moran or other algorithm.
