### ISSUE TITLE
Issue with Numba < 0.47

### ISSUE THREAD

**Issue by stuartarchibald** [pysal/esda#142]
This was reported on the Numba issue tracker, unfortunately with no reproducer: https://github.com/numba/numba/issues/6059 and I'm afraid I'm not familiar enough with this package to construct one. However, guessing from the traceback, I think ESDA might need to pin Numba >= 0.47 to ensure this problem isn't hit. I can prepare a PR if it helps?

**Comment by ljwolf** [comment]
Hi, thanks for the feedback! We don't *require* numba, although we do recommend that users have it so that they get the fastest verisons of our algorithms out there. 

We will take a look at recommending `numba > .50.1`, since we also hit this when building the numba implementation, or at least documenting the issue.

**Comment by stuartarchibald** [comment]
Great, thanks for adding #143, please do close this as you see fit!
If you've any issues with Numba itself please feel free to raise them on our [issue tracker](https://github.com/numba/numba/issues) too :)
Thanks again!
