### ISSUE TITLE
MoranI_local_BI: reshape(-1, cardinality) cannot reshape array of size 0 into shape (0)

### ISSUE THREAD

**Issue by tjwjy** [pysal/esda#167]
when there is an island in the geopandas, using sea version 2.3.6 will generate the value error. Version 2.2.0 will not.

**Comment by sjsrey** [comment]
Thanks for reporting this. Would it be possible to get  a  [mwe](https://en.wikipedia.org/wiki/Minimal_working_example) so we can investigate further?

**Comment by danekwo** [comment]
Hello,
I believe I am having a similar issue.

I am trying to plot the High-High areas in an image by calculating the Local Moran's I values. This worked with images that had only numbers as their pixel intensity values, but I've been informed that some of those 0s are meant to be NaN, as they're not part of the area I am supposed to analyse - I imagine this is because it would have an effect on which areas are considered High/Low.

In order to work around this, I decided to modify the weight matrix of each pixel point so that pixels with a value of NaN would have a weight of 0. This results in many islands, as there are many pixels around the edges that are just NaNs. This seems to break the calculation of Local Moran's.
The error I'm running into at the moment is the following: "cannot reshape array of size 0 into shape (0)". 

I'm using libpysal 4.5.1 and esda 2.4.1 - I'm also attaching a list of my "conda list" output.

Code I'm working on: https://drive.google.com/file/d/1Anr4WxqiRoEOfs1CPDvfQn0GATS-eFrt/view?usp=sharing
[Conda-list.txt](https://github.com/pysal/esda/files/6902233/Conda-list.txt)

**Comment by sjsrey** [comment]
For building efficient weights to use with rasters, you may want to look at https://gist.github.com/MgeeeeK/15426217eb5f368ca0ff12f66c2b5823 and the API  https://pysal.org/libpysal/api.html#weights-tools-to-interface-with-rasters

Let us know if this helps or if you are still having issues.

**Comment by jGaboardi** [comment]
Resolved in #190.
