### ISSUE TITLE
G_Local: EG_sim and seG_sim are scalar

### ISSUE THREAD

**Issue by rsbivand** [pysal/esda#53]
In Moran_Local(), EI_sim and seI_sim are nx1 arrays, so differentiating the outcome by observation. In G_Local, EG_sim and seG_sim are scalar, in some cases that I've looked at narrowing the z_sim distribution compared to Zs, the analytical distribution. 

Was this intended, or should G_Local be reviewed around line 376 in esda/getisord.py? Are there a vectorised sum() and std() methods to apply to an array row-wise?

**Comment by sjsrey** [comment]
Thanks for spotting this. It is a bug and was not intentional as the treatment in G_Local() should mirror that of Moran_Local() in the treatment of the z_sim distributions. The original code seems to be a case of a [cut and paste error](https://github.com/pysal/esda/blame/master/esda/getisord.py#L376).

Will be submitting a fix shortly.

**Comment by rsbivand** [comment]
OK, thanks!

**Comment by weikang9009** [comment]
corrected by https://github.com/pysal/esda/pull/54

**Comment by rsbivand** [comment]
Thanks!
